apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ClientPolicy
metadata:
  name: client-policy
spec:
  match:
    kinds:
      - apiGroups:
          - ''
        kinds:
          - Pod
          - Namespace
    scope: '*'
