apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: openshift-gatekeeper-system
spec:
  sync:
    syncOnly:
      - group: user.openshift.io
        kind: Group
        version: v1
  validation:
    traces:
      - dump: ALL
        kind:
          kind: Pod
        user: 'na-kube:admin'
